In [1]:
# numpy.expand_dims(a, axis) testing
import numpy as np

In [2]:
x = np.array([1, 2])
x.shape
# x.shape (2,)

(2,)

In [3]:
y = np.expand_dims(x, axis=0)
y.shape
# y.shape (1, 2)
print(y)
# y [[1 2]]

(1, 2)

In [5]:
y = np.expand_dims(x, axis=1)
print(y)
# [[1]
#  [2]]

print(y.shape)
# y.shape (2, 1)

[[1]
 [2]]
(2, 1)


In [6]:
A = np.array([[1, 1], [2, 2], [3, 3]])
A.shape
# A.shape (3, 2)

(3, 2)

In [9]:
A = np.array([[1, 2, 3], [1, 2, 3]])
print(A)
# [[1 2 3]
#  [1 2 3]]

print(A.shape)
# A.shape (2, 3)

[[1 2 3]
 [1 2 3]]
(2, 3)


In [10]:
# 在第 “axis” 維 加一個維度出來 原先的 “維” 則推到右邊去 (https://www.zhihu.com/question/265545749)
A0 = np.expand_dims(A, axis=0)
print(A0)
# [[[1 2 3]
#   [1 2 3]]]

print(A0.shape)
# A0.shape

[[[1 2 3]
  [1 2 3]]]
(1, 2, 3)


In [11]:
A1 = np.expand_dims(A, axis=1)
print(A1)
# [[[1 2 3]]

#  [[1 2 3]]]

print(A1.shape)
# A1.shape 

[[[1 2 3]]

 [[1 2 3]]]
(2, 1, 3)


In [13]:
A2 = np.expand_dims(A, axis=2)
print(A2)
# [[[1]
#   [2]
#   [3]]

#  [[1]
#   [2]
#   [3]]]

print(A2.shape)
# A2.shape (2, 3, 1)

# A3 = np.expand_dims(A, axis=3)
# AxisError: axis 3 is out of bounds for array of dimension 3

[[[1]
  [2]
  [3]]

 [[1]
  [2]
  [3]]]
(2, 3, 1)
